version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
  install:
    commands:
      - bash download-content.sh
      - cd labs-2018
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'labs-2018/dist/**/*'
