version: 0.2

phases:
  install:
    commands:
      - bash download-content.sh
      - cd labs-2018
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'labs-2018/dist/**/*'
